server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:demo_spring}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:admin!@#}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations:
     - classpath:db/migration